---
title: "TSL-Galaxy-HandBook"
author: "Ram Krishna Shrestha"
date: "08/03/2017"
output: bookdown::gitbook

site: bookdown::bookdown_site
description: "A Hand Book to learn Galaxy platform for bioinformatic data analysis for a new user in TSL"
---

# Preface

The purpose of this handbook is to give a new user an introduction to the Galaxy environment for bioinformatics.

This handbook will introduce you to the TSL Galaxy installation, it's basic functionality, show you how to do some straightforward data manipulation and analysis, visualization and creating workflows.

# Prerequisites

There are no formal prerequisites for this. To access TSL Galaxy, you will need to be on the NBI site (or accessing via VPN).

# Accessing TSL Galaxy

## Registration

  First, you will need to a registered TSL account or a TSL email ID. Then, you will need to email Dan MacLean (Head of Bioinformatics), Ram Krishna Shrestha (Bioinformatics support) and Martin Page (web developer) with a request to access TSL galaxy. We will then add your TSL account/Email to the TSL Galaxy user group and let you know. Now, you are ready to login.

## Login to TSL Galaxy

  Go to <galaxy.tsl.ac.uk> in your web browser, which will take you to login page. Enter your TSL username or TSL email id and then the password.